spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  session:
    redis:
      namespace: cloud:sess
      flush-mode: on_save
      save-mode: on_set_attribute

server:
  port: 8080
  tomcat:
    max-part-count: 100
  servlet:
    session:
      timeout: 30m
  forward-headers-strategy: framework

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket-name: ${MINIO_BUCKET}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
