spring:
  application:
    name: cloud-file-storage
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: create-drop
    open-in-view: false
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8080
#  servlet:
#    session:
#      cookie:
#        name: SESSION       # Имя cookie, в которой хранится идентификатор сессии
#        http-only: true     # Cookie нельзя читать из JS (защита от XSS)
#        same-site: Lax      # Политика SameSite (Lax = передаётся при навигации внутри сайта, но не всегда во внешних переходах)
#        secure: false       # Cookie будет передаваться и по HTTP, и по HTTPS. При true — только по HTTPS (рекомендуется на проде)
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ROOT_USER:test}
  secret-key: ${MINIO_ROOT_PASSWORD:12345678}
#  bucket-name: ${MINIO_BUCKET:files}
