spring:
  application:
    name: cloud-file-storage

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  session:
    redis:
      namespace: cloud:sess
      flush-mode: on_save
      save-mode: on_set_attribute

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB

server:
  port: 8080
  tomcat:
    max-part-count: 100
  servlet:
    session:
      timeout: 30m

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ROOT_USER:admin}
  secret-key: ${MINIO_ROOT_PASSWORD:12345678}
  bucket-name: ${MINIO_BUCKET:user-files}
